services:
  - type: web
    name: shareway-trip-planning-matching-service
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 1
      - key: SPRING_FLYWAY_SCHEMAS
        sync: false
      - key: SPRING_FLYWAY_DEFAULT_SCHEMA
        sync: false
