create table trip_requests (
    id bigint generated by default as identity primary key,
    passenger_id bigint not null,
    origin_label varchar(160) not null,
    destination_label varchar(160) not null,
    operation_zone varchar(120) not null,
    origin_lat numeric(9, 6) not null,
    origin_lng numeric(9, 6) not null,
    destination_lat numeric(9, 6) not null,
    destination_lng numeric(9, 6) not null,
    travel_date date not null,
    earliest_departure time not null,
    latest_departure time not null,
    seats_requested integer not null,
    status varchar(20) not null,
    created_at timestamp with time zone not null
);

create index idx_trip_requests_zone_date
    on trip_requests (operation_zone, travel_date);

create table driver_availabilities (
    id bigint generated by default as identity primary key,
    driver_id bigint not null,
    operation_zone varchar(120) not null,
    available_date date not null,
    start_time time not null,
    end_time time not null,
    available_seats integer not null
);

create index idx_driver_availabilities_matching
    on driver_availabilities (operation_zone, available_date, start_time, end_time, available_seats);

create table match_proposals (
    id bigint generated by default as identity primary key,
    trip_request_id bigint not null references trip_requests(id),
    driver_id bigint not null,
    estimated_fare numeric(8, 2) not null,
    estimated_duration_minutes integer not null,
    status varchar(20) not null,
    created_at timestamp with time zone not null
);

create index idx_match_proposals_trip_request
    on match_proposals (trip_request_id, created_at desc);
